return {
  {
    id = "plenary.nvim",
    src = "https://github.com/nvim-lua/plenary.nvim",
    dependency = true,
    env = { vscode = "any" },
  },
  {
    id = "nvim-web-devicons",
    src = "https://github.com/nvim-tree/nvim-web-devicons",
    feature = "ui.icons",
    env = { vscode = false },
  },
  {
    id = "mason.nvim",
    src = "https://github.com/mason-org/mason.nvim",
    feature = "lsp.server_manager",
    env = { vscode = false },
  },
  {
    id = "mason-lspconfig.nvim",
    src = "https://github.com/mason-org/mason-lspconfig.nvim",
    feature = "lsp.server_manager",
    dependencies = { "mason.nvim", "nvim-lspconfig" },
    env = { vscode = false },
  },
  {
    id = "nvim-lspconfig",
    src = "https://github.com/neovim/nvim-lspconfig",
    feature = "lsp.runtime",
    env = { vscode = false },
    setup = "plugins.specs.lsp",
  },
  {
    id = "telescope.nvim",
    src = "https://github.com/nvim-telescope/telescope.nvim",
    version = "v0.2.1",
    feature = "search.picker",
    dependencies = { "plenary.nvim" },
    env = { vscode = false },
    setup = "plugins.specs.telescope",
  },
  {
    id = "yazi.nvim",
    src = "https://github.com/mikavilpas/yazi.nvim",
    version = "main",
    feature = "file.explorer",
    dependencies = { "plenary.nvim" },
    env = { vscode = false },
    setup = "plugins.specs.yazi",
  },
  {
    id = "incline.nvim",
    src = "https://github.com/b0o/incline.nvim",
    feature = "ui.status",
    dependencies = { "gitsigns.nvim", "nvim-web-devicons" },
    env = { vscode = false },
    setup = "plugins.specs.incline",
  },
  {
    id = "gitsigns.nvim",
    src = "https://github.com/lewis6991/gitsigns.nvim",
    feature = "git.signs",
    env = { vscode = false },
    setup = "plugins.specs.gitsigns",
  },
  {
    id = "diffview.nvim",
    src = "https://github.com/sindrets/diffview.nvim",
    feature = "git.diff_view",
    env = { vscode = false },
    setup = "plugins.specs.diffview",
  },
  {
    id = "gitlinker.nvim",
    src = "https://github.com/ruifm/gitlinker.nvim",
    feature = "git.linker",
    dependencies = { "plenary.nvim" },
    env = { vscode = "any" },
    setup = "plugins.specs.gitlinker",
  },
  {
    id = "autoclose.nvim",
    src = "https://github.com/m4xshen/autoclose.nvim",
    feature = "editing.autoclose",
    env = { vscode = false },
    setup = "plugins.specs.autoclose",
  },
  {
    id = "tree-sitter-manager.nvim",
    src = "https://github.com/romus204/tree-sitter-manager.nvim",
    feature = "treesitter.parser_manager",
    env = { vscode = "any" },
    setup = "plugins.specs.treesitter",
  },
  {
    id = "nvim-treesitter-textobjects",
    src = "https://github.com/nvim-treesitter/nvim-treesitter-textobjects",
    version = "main",
    feature = "treesitter.textobjects",
    env = { vscode = "any" },
    setup = "plugins.specs.treesitter_textobjects",
  },
  {
    id = "nvim-treesitter-context",
    src = "https://github.com/nvim-treesitter/nvim-treesitter-context",
    feature = "treesitter.context",
    env = { vscode = false },
    setup = "plugins.specs.treesitter_context",
  },
  {
    id = "toggleterm.nvim",
    src = "https://github.com/akinsho/toggleterm.nvim",
    feature = "terminal",
    env = { vscode = false },
    setup = "plugins.specs.toggleterm",
  },
  {
    id = "conform.nvim",
    src = "https://github.com/stevearc/conform.nvim",
    feature = "format",
    env = { vscode = false },
    setup = "plugins.specs.conform",
  },
  {
    id = "nvim-dap",
    src = "https://github.com/mfussenegger/nvim-dap",
    feature = "debug",
    env = { vscode = false },
    setup = "plugins.specs.dap",
  },
  {
    id = "nvim-dap-ui",
    src = "https://github.com/rcarriga/nvim-dap-ui",
    feature = "debug.ui",
    dependencies = { "nvim-dap", "nvim-nio" },
    env = { vscode = false },
  },
  {
    id = "nvim-dap-virtual-text",
    src = "https://github.com/theHamsta/nvim-dap-virtual-text",
    feature = "debug.virtual_text",
    dependencies = { "nvim-dap" },
    env = { vscode = false },
  },
  {
    id = "nvim-dap-python",
    src = "https://github.com/mfussenegger/nvim-dap-python",
    feature = "debug.python",
    dependencies = { "nvim-dap" },
    env = { vscode = false },
  },
  {
    id = "nvim-nio",
    src = "https://github.com/nvim-neotest/nvim-nio",
    dependency = true,
    env = { vscode = false },
  },
}
