[[plugins]]
repo = 'cohama/lexima.vim'
hook_add = '''

let g:lexima_enable_basic_rules = 1
let g:lexima_enable_endwise_rules = 1
let g:lexima_enable_newline_rules = 1

call lexima#add_rule({'char': '<C-h>', 'at': '(\%#)',   'delete': 1})
call lexima#add_rule({'char': '<C-h>', 'at': '{\%#}',   'delete': 1})
call lexima#add_rule({'char': '<C-h>', 'at': '\[\%#\]', 'delete': 1})
call lexima#add_rule({'char': '<C-h>', 'at': '"\%#"',   'delete': 1})
call lexima#add_rule({'char': '<C-h>', 'at': "'\\%#'",  'delete': 1})
call lexima#add_rule({'char': '<C-h>', 'at': '`\%#`',   'delete': 1})

call lexima#add_rule({'char': '<C-w>', 'at': '(\%#)',   'delete': 1})
call lexima#add_rule({'char': '<C-w>', 'at': '{\%#}',   'delete': 1})
call lexima#add_rule({'char': '<C-w>', 'at': '\[\%#\]', 'delete': 1})
call lexima#add_rule({'char': '<C-w>', 'at': '"\%#"',   'delete': 1})
call lexima#add_rule({'char': '<C-w>', 'at': "'\\%#'",  'delete': 1})
call lexima#add_rule({'char': '<C-w>', 'at': '`\%#`',   'delete': 1})

'''
