[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'VimEnter'
hook_source = '''

" Customize global settings

" Set sources used.
call ddc#custom#patch_global('sources', ['vim-lsp', 'around'])

" Change source options
call ddc#custom#patch_global('sourceOptions', {
    \ 'vim-lsp': {
    \   'matchers': ['matcher_head'],
    \   'sorters': ['sorter_rank'],
    \   'mark': 'lsp',
    \ },
    \ 'around': {
    \   'matchers': ['matcher_head'],
    \   'sorters': ['sorter_rank'],
    \   'mark': 'A',
    \ },
    \ })

" Change source params
call ddc#custom#patch_global('sourceOptions', {
    \ '_': {
    \   'maxSize': 50,
    \ }
    \ })

" Mappings
" <TAB>: completion.
inoremap <silent><expr> <TAB>
\ pumvisible() ? '<C-n>' :
\ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
\ '<TAB>' : ddc#manual_complete()
" <S-TAB>: completion back.
inoremap <expr><S-TAB>  pumvisible() ? '<C-p>' : '<C-h>'
" Use ddc.
call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'shun/ddc-vim-lsp'
on_source = 'ddc.vim'
