[[plugins]]
repo = "airblade/vim-gitgutter"
hook_add = '''
let g:gitgutter_override_sign_column_highlight=0
let g:gitgutter_max_signs=-1
set updatetime=100 " diff更新の周期 [ms]
set signcolumn=yes " 常に左の列を表示
highlight! link SignColumn LineNr " Sign Columnのハイライトを無効化
'''
