[[plugins]]
repo='prabirshrestha/vim-lsp'
hook_add = '''
if executable('ccls')
   au User lsp_setup call lsp#register_server({
      \ 'name': 'ccls',
      \ 'cmd': {server_info->['ccls']},
      \ 'root_uri': {server_info->lsp#utils#path_to_uri(lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), 'compile_commands.json'))},
      \ 'initialization_options': { 'cache': { 'directory': '/tmp/ccls-cache'} },
      \ 'whitelist': ['c', 'cpp', 'objc', 'objcpp', 'cc'],
      \ })
endif

let g:lsp_diagnostics_enabled = 1
let g:lsp_diagnostics_echo_cursor = 1
let g:asyncomplete_auto_popup = 1
let g:lsp_text_edit_enabled = 1
let g:lsp_semantic_enabled = 1

autocmd BufWritePre <buffer> LspDocumentFormatSync

'''
