version: 2
tools:
  python-flake8: &python-flake8
    lint-command: 'flake8 --max-line-length 88 --ignore=E203,E503,E504,W503 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  python-mypy: &python-mypy
    lint-command: 'mypy --show-column-numbers'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  python-black: &python-black
    format-command: 'black --quiet -'
    format-stdin: true

  python-isort: &python-isort
    format-command: 'isort --quiet -'
    format-stdin: true

languages:
  python:
    - <<: *python-flake8
#    - <<: *python-mypy
    - <<: *python-black
    - <<: *python-isort
