[[plugins]]
repo = 'liuchengxu/vista.vim'
depends = ['nvim-lspconfig']
hook_add = '''
" <Vista.vim repo>/autoload/vista/executive にあるファイル名で指定
let g:vista_default_executive = 'nvim_lsp'

function! NearestMethodOrFunction() abort
  return get(b:, 'vista_nearest_method_or_function', '')
endfunction

" By default vista.vim never run if you don't call it explicitly.
"
" If you want to show the nearest function in your statusline automatically,
" you can add the following line to your vimrc
" FIXME(anyone): Use VimEnter
autocmd InsertEnter * call vista#RunForNearestMethodOrFunction()
'''
