[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'VimEnter'
hook_source = '''
"lua require('nvim_lsp_cfg')

set completeopt-=preview " Previewを出さない

" 保存時にフォーマットする
" 10000ms(10s) でtimeoutする
" フォーマットしたくないときは :noautocmd w と打つ
autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync({}, 10000)

'''

[[plugins]]
repo = 'glepnir/lspsaga.nvim'
on_source = 'nvim-lspconfig'
branch = 'main'
hook_source = '''
lua require('lspsaga_cfg')
function! ShowSymbol() abort
  return v:lua.symbol_string()
endfunction
'''

[[plugins]]
repo = 'hrsh7th/nvim-cmp'
on_source = 'nvim-lspconfig'
hook_source = '''
lua require('nvim_cmp_cfg')
'''

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-path'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/cmp-vsnip'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
on_source = 'nvim-cmp'

[[plugins]]
repo = 'ray-x/lsp_signature.nvim'
if = "has('nvim')"
on_source = 'nvim-lspconfig'
hook_source= '''
lua require('lsp_signature_cfg')
'''

[[plugins]]
repo = 'onsails/lspkind-nvim'
on_source = 'nvim-cmp'
hook_source= '''
" gray
highlight! CmpItemAbbrDeprecated guibg=NONE gui=strikethrough guifg=#808080
" blue
highlight! CmpItemAbbrMatch guibg=NONE guifg=#569CD6
highlight! CmpItemAbbrMatchFuzzy guibg=NONE guifg=#569CD6
" light blue
highlight! CmpItemKindVariable guibg=NONE guifg=#9CDCFE
highlight! CmpItemKindInterface guibg=NONE guifg=#9CDCFE
highlight! CmpItemKindText guibg=NONE guifg=#9CDCFE
" pink
highlight! CmpItemKindFunction guibg=NONE guifg=#C586C0
highlight! CmpItemKindMethod guibg=NONE guifg=#C586C0
" front
highlight! CmpItemKindKeyword guibg=NONE guifg=#D4D4D4
highlight! CmpItemKindProperty guibg=NONE guifg=#D4D4D4
highlight! CmpItemKindUnit guibg=NONE guifg=#D4D4D4
'''
