[[plugins]]
repo = 'mfussenegger/nvim-dap'
on_event = 'VimEnter'
hook_source = '''
lua require('nvim_dap_cfg')
'''

[[plugins]]
repo = 'rcarriga/nvim-dap-ui'
on_source = 'nvim-dap'

[[plugins]]
repo = 'theHamsta/nvim-dap-virtual-text'
on_source = 'nvim-dap'

[[plugins]]
repo = 'mfussenegger/nvim-dap-python'
on_source = 'nvim-dap'
